feat: добавить функционал для ветки add-controllers по ТЗ из спринта
IvanPozhidaev/java-shareit pull request #1
Opened 2023-06-08 10:35 UTC by IvanPozhidaev

реализовать модели данных для item, request, booking; добавить исключения; создать dto и мапперы

2023-06-09 17:09 UTC, alexache requested changes

2023-06-09 17:09 UTC, alexache commented on src/main/java/ru/practicum/shareit/error_handler/ErrorHandler.java
> +package ru.practicum.shareit.error_handler;
В именах пакетов не приняты нижние подчеркивания

2023-06-09 17:09 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/ItemDto.java
> +    private String name;
Не хватает валидаций на ДТО

2023-06-09 17:09 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long owner;
Желательно иметь объект владельца, а не толлко айди

2023-06-09 17:09 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemValidationService.java
> +        List<User> result = users.stream().filter(user -> user.getId() == ownerId).collect(Collectors.toList());
Это очень странный запрос, почему бы не завесьи запрос получения пользователя по айди?

2023-06-09 17:09 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemValidationService.java
> +    public void validateItem(Item item) {
Валидации более принто делать из контроллера, нежели сервиса (не считая проверок с использованием БД)

2023-06-09 17:09 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/impl/InMemoryItemDaoImpl.java
> +        for (Item item : items.values()) {
Полный перебор всех вещей не очень оптимально. Лучше завести доп мапу для маппинга пользователя на список вещей пользователя

2023-06-09 17:09 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/impl/InMemoryItemDaoImpl.java
> +        for (Item item : items.values()) {
(опционально) наглядние будет писать с помощью стримов

2023-06-09 17:09 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/model/UserDto.java
> +    private String name;
Почему бы не делать валидации аннотациями?

2023-06-10 06:59 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/error_handler/ErrorHandler.java
> +package ru.practicum.shareit.error_handler;
Исправлено

2023-06-11 09:08 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/user/model/UserDto.java
> +    private String name;
Добавлены аннотации для DTO.

2023-06-11 09:20 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long owner;
В данном случае хотел бы сохранить свою реализацию, т.к. связь объектов через айди позволяет избежать сильной связи, а также эффективнее по ресурсам.

2023-06-11 09:20 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/item/model/ItemDto.java
> +    private String name;
Валидации добавлены.

2023-06-11 09:21 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/item/service/ItemValidationService.java
> +    public void validateItem(Item item) {
Валидации перенесены в контроллер.

2023-06-11 09:38 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/item/storage/impl/InMemoryItemDaoImpl.java
> +        for (Item item : items.values()) {
Переделано.

2023-06-11 09:38 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/item/storage/impl/InMemoryItemDaoImpl.java
> +        for (Item item : items.values()) {
Переделано.

2023-06-11 09:48 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/item/service/ItemValidationService.java
> +        List<User> result = users.stream().filter(user -> user.getId() == ownerId).collect(Collectors.toList());
Переделано.

2023-06-11 20:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long owner;
В следующем спринте уже понадобится переделать на полноценные объекты в ссылках

2023-06-11 20:34 UTC, alexache approved these changes

2023-06-12 03:33 UTC, merged