Add bookings
IvanPozhidaev/java-shareit pull request #2
Opened 2023-06-28 03:55 UTC by IvanPozhidaev

2023-06-28 21:19 UTC, alexache requested changes

2023-06-28 21:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    public static final String ITEM_COLUMN_NAME = "item";
Нужно ли делать эти константы публичными? И нужны ли они, если используются лишь единожды

2023-06-28 21:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    public boolean equals(Object o) {
Такие equals/hashcode нельзя писать для JPA моделей - есть нюансы и нужно подумать нужны ли они

2023-06-28 21:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("select b from bookings b " +
Нельзя ли попробовать обойтись без @query?

2023-06-28 21:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +            "where b.booker.id = ?1 " +
К джоин таблицам тоже ведь можно обращаться? использую именование метода

2023-06-28 21:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private State parseState(String state) {
Такой метод логичнее в State енаме

2023-06-28 21:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDetailedDto.java
> +    private User booker;
Не должно быть моделей в ДТО?

2023-06-28 21:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +    private User booker;
Не должно быть моделей в ДТО

2023-06-28 21:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                      @Min(MIN_ID_VALUE)
Для работы таких аннотаций, нужен @Validated на классе

2023-06-28 21:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<Item> userItems = itemRepository.findAll()
Это не лучший способ, лучше сделать полноценный запрос к базе с поиском по владельцу

2023-06-28 21:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<User> result = users.stream().filter(user -> user.getId() == ownerId).collect(Collectors.toList());
тоже лучше сделать полноценный запрос к базе

2023-06-28 21:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            List<Comment> comments = commentRepository.findByItemId(item.getId());
Запросы к базе в цикле под запретом

2023-06-28 21:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<Booking> lastBooking = bookingRepository.findLastBookingsByItemIdAndEndIsBeforeAndStatusIs(
Как и эти запросы к базе в цикле (этот метод вызывается в цикле). Нужно получать информацию по списку вещей сразу

2023-06-28 21:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/User.java
> +@Entity(name = "users")
И @Entity и @Table?

2023-07-01 07:16 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    public boolean equals(Object o) {
Убраны лишние методы

2023-07-01 07:25 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                      @Min(MIN_ID_VALUE)
Добавлены аннотации

2023-07-01 07:44 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    public static final String ITEM_COLUMN_NAME = "item";
Константы удалены

2023-07-01 08:23 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("select b from bookings b " +
Метод заменён на запросный

2023-07-01 11:25 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private State parseState(String state) {
Перенесено

2023-07-01 12:13 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            List<Comment> comments = commentRepository.findByItemId(item.getId());
Метод переделан.

2023-07-02 03:57 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/user/User.java
> +@Entity(name = "users")
В данном случае да, и то и другое. Иначе не работает.

2023-07-02 04:18 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<User> result = users.stream().filter(user -> user.getId() == ownerId).collect(Collectors.toList());
Переделано.

2023-07-03 05:24 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDetailedDto.java
> +    private User booker;
Убрано

2023-07-03 05:24 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +    private User booker;
Убрано

2023-07-03 12:40 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<Booking> lastBooking = bookingRepository.findLastBookingsByItemIdAndEndIsBeforeAndStatusIs(
Метод больше не вызывается в цикле.

2023-07-04 09:31 UTC, alexache requested changes

2023-07-04 09:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
>      private Item item;
Еще один класс модели остался

2023-07-04 09:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDetailedDto.java
>      private Item item;
Все еще класс модели, а не ДТО

2023-07-04 09:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<ItemDto> result = itemRepository.findAll()
Это все же не запрос к базе получения вещей определенного владельца. Это получение всех вещей и фильтрация на уровне Джавы

2023-07-04 09:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    List<Comment> comments = commentRepository.findByItemId(item.getId());
Это запрос к базе в цикле (проходишь по списку вещей и для каждой отдельной вещи делаешь запрос получения комментариев. Нужно получать комментарии сразу по списку вещей

2023-07-04 09:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .map(item -> constructItemDtoForOwner(item, now, sortDesc, commentRepository.findByItemId(item.getId())))
.map() ничем не отличается от цикла, это будет циклически вызвано для каждой отдельно взятой вещи, а нужно обходится запросами сразу по спискам сущностей

2023-07-06 10:33 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
>      private Item item;
Переделано.

2023-07-06 12:04 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDetailedDto.java
>      private Item item;
Переделано.

2023-07-07 18:14 UTC, alexache approved these changes

2023-07-07 18:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<ItemDto> itemDtos = items.stream().map(item -> {
Уже лучше, что нет запроса к базе в цикле, но остался полный обход списка внутри цикла :) Это просто неоптимально и квадратичная сложность там, где не нужно. Можно переложить в мапу с ключем айди вещи на бронирования или комментарии соответственно. Такой маппинг получится за один проход списка

2023-07-07 18:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .map(item -> ItemMapper.toDto(item, filterCommentsByItemId(comments, item.getId())))
Похожий комментарий про неоптимальность (можно сделат ьлучше)

2023-07-08 02:08 UTC, merged