feat:add-item-requests
IvanPozhidaev/java-shareit pull request #3
Opened 2023-07-11 08:55 UTC by IvanPozhidaev

2023-07-12 18:53 UTC, alexache requested changes

2023-07-12 18:53 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/Item.java
>      private Long owner;
Все еще хорошо бы перейти на User вместо long

2023-07-12 18:53 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    private Long requestId;
А здесь перейти на ItemRequest вместо числа

2023-07-12 18:53 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .map(item -> constructItemDtoForOwner(item, filterCommentsByItemId(comments, item.getId())))
Это вызов метода в цикле с запросом к базе - так не стоит делать

2023-07-12 18:53 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingService bookingService;
Не хватает модификаторов доступа у полей

2023-07-12 18:53 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    ItemService itemService;
Не хватает модификатора доступа

2023-07-13 08:01 UTC, IvanPozhidaev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingService bookingService;
Добавлено.

2023-07-13 08:01 UTC, IvanPozhidaev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    ItemService itemService;
Добавлено.

2023-07-13 08:35 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .map(item -> constructItemDtoForOwner(item, filterCommentsByItemId(comments, item.getId())))
Переделано.

2023-07-16 22:57 UTC, alexache approved these changes

2023-07-16 22:57 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        System.out.println(LocalDateTime.now());
Такие отладочные логи лучше подчищать

2023-07-16 22:57 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query("select i from items i where i.owner.id = ?1")
Такого рода запрос уже довольно легко сделать через именование метода

2023-07-17 02:21 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        System.out.println(LocalDateTime.now());
Убрано.

2023-07-17 02:21 UTC, IvanPozhidaev commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query("select i from items i where i.owner.id = ?1")
Переделано.

2023-07-17 02:22 UTC, merged