Add docker
IvanPozhidaev/java-shareit pull request #4
Opened 2023-07-21 04:52 UTC by IvanPozhidaev

2023-07-23 07:06 UTC, alexache requested changes

2023-07-23 07:06 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    private boolean isStartBeforeEnd(BookingPostDto dto) {
Это больше применимо к контроллеру, чем клиенту

2023-07-23 07:06 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/item/dto/CreateCommentDto.java
> -    @NotBlank(groups = Create.class)
Отчего теперь без валидаций?

2023-07-23 07:06 UTC, alexache commented on pom.xml
>  	<dependencies>
Родительскому модулю лучше иметь только dependencyManagement/pluginManagement, а конкретные зависимости оставлять на усмотрение модулей

2023-07-23 13:29 UTC, IvanPozhidaev commented on pom.xml
>  	<dependencies>
Переделано.

2023-07-23 15:27 UTC, IvanPozhidaev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    private boolean isStartBeforeEnd(BookingPostDto dto) {
Переделано.

2023-07-24 02:37 UTC, IvanPozhidaev commented on gateway/src/main/java/ru/practicum/shareit/item/dto/CreateCommentDto.java
> -    @NotBlank(groups = Create.class)
Упустил. Добавил валидацию.

2023-07-24 13:12 UTC, alexache approved these changes

2023-07-24 14:34 UTC, merged